/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesSelectBusinessRouteImport } from './routes/businesses/select-business'
import { Route as BusinessesRegisterRouteImport } from './routes/businesses/register'
import { Route as BusinessesBusinessslugRouteImport } from './routes/businesses/$businessslug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as BusinessesBusinessslugIndexRouteImport } from './routes/businesses/$businessslug/index'
import { Route as BusinessesBusinessslugGroupsIndexRouteImport } from './routes/businesses/$businessslug/groups/index'
import { Route as BusinessesBusinessslugEmployeesIndexRouteImport } from './routes/businesses/$businessslug/employees/index'
import { Route as BusinessesBusinessslugGroupsCreateRouteImport } from './routes/businesses/$businessslug/groups/create'
import { Route as BusinessesBusinessslugGroupsGroupslugRouteImport } from './routes/businesses/$businessslug/groups/$groupslug'
import { Route as BusinessesBusinessslugEmployeesCreateRouteImport } from './routes/businesses/$businessslug/employees/create'
import { Route as BusinessesBusinessslugEmployeesEmployeeidRouteImport } from './routes/businesses/$businessslug/employees/$employeeid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSelectBusinessRoute =
  BusinessesSelectBusinessRouteImport.update({
    id: '/businesses/select-business',
    path: '/businesses/select-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessesRegisterRoute = BusinessesRegisterRouteImport.update({
  id: '/businesses/register',
  path: '/businesses/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessslugRoute = BusinessesBusinessslugRouteImport.update({
  id: '/businesses/$businessslug',
  path: '/businesses/$businessslug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessslugIndexRoute =
  BusinessesBusinessslugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugGroupsIndexRoute =
  BusinessesBusinessslugGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugEmployeesIndexRoute =
  BusinessesBusinessslugEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugGroupsCreateRoute =
  BusinessesBusinessslugGroupsCreateRouteImport.update({
    id: '/groups/create',
    path: '/groups/create',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugGroupsGroupslugRoute =
  BusinessesBusinessslugGroupsGroupslugRouteImport.update({
    id: '/groups/$groupslug',
    path: '/groups/$groupslug',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugEmployeesCreateRoute =
  BusinessesBusinessslugEmployeesCreateRouteImport.update({
    id: '/employees/create',
    path: '/employees/create',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)
const BusinessesBusinessslugEmployeesEmployeeidRoute =
  BusinessesBusinessslugEmployeesEmployeeidRouteImport.update({
    id: '/employees/$employeeid',
    path: '/employees/$employeeid',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugRouteWithChildren
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug/': typeof BusinessesBusinessslugIndexRoute
  '/businesses/$businessslug/employees/$employeeid': typeof BusinessesBusinessslugEmployeesEmployeeidRoute
  '/businesses/$businessslug/employees/create': typeof BusinessesBusinessslugEmployeesCreateRoute
  '/businesses/$businessslug/groups/$groupslug': typeof BusinessesBusinessslugGroupsGroupslugRoute
  '/businesses/$businessslug/groups/create': typeof BusinessesBusinessslugGroupsCreateRoute
  '/businesses/$businessslug/employees': typeof BusinessesBusinessslugEmployeesIndexRoute
  '/businesses/$businessslug/groups': typeof BusinessesBusinessslugGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugIndexRoute
  '/businesses/$businessslug/employees/$employeeid': typeof BusinessesBusinessslugEmployeesEmployeeidRoute
  '/businesses/$businessslug/employees/create': typeof BusinessesBusinessslugEmployeesCreateRoute
  '/businesses/$businessslug/groups/$groupslug': typeof BusinessesBusinessslugGroupsGroupslugRoute
  '/businesses/$businessslug/groups/create': typeof BusinessesBusinessslugGroupsCreateRoute
  '/businesses/$businessslug/employees': typeof BusinessesBusinessslugEmployeesIndexRoute
  '/businesses/$businessslug/groups': typeof BusinessesBusinessslugGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugRouteWithChildren
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug/': typeof BusinessesBusinessslugIndexRoute
  '/businesses/$businessslug/employees/$employeeid': typeof BusinessesBusinessslugEmployeesEmployeeidRoute
  '/businesses/$businessslug/employees/create': typeof BusinessesBusinessslugEmployeesCreateRoute
  '/businesses/$businessslug/groups/$groupslug': typeof BusinessesBusinessslugGroupsGroupslugRoute
  '/businesses/$businessslug/groups/create': typeof BusinessesBusinessslugGroupsCreateRoute
  '/businesses/$businessslug/employees/': typeof BusinessesBusinessslugEmployeesIndexRoute
  '/businesses/$businessslug/groups/': typeof BusinessesBusinessslugGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/$businessslug'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug/'
    | '/businesses/$businessslug/employees/$employeeid'
    | '/businesses/$businessslug/employees/create'
    | '/businesses/$businessslug/groups/$groupslug'
    | '/businesses/$businessslug/groups/create'
    | '/businesses/$businessslug/employees'
    | '/businesses/$businessslug/groups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug'
    | '/businesses/$businessslug/employees/$employeeid'
    | '/businesses/$businessslug/employees/create'
    | '/businesses/$businessslug/groups/$groupslug'
    | '/businesses/$businessslug/groups/create'
    | '/businesses/$businessslug/employees'
    | '/businesses/$businessslug/groups'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/$businessslug'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug/'
    | '/businesses/$businessslug/employees/$employeeid'
    | '/businesses/$businessslug/employees/create'
    | '/businesses/$businessslug/groups/$groupslug'
    | '/businesses/$businessslug/groups/create'
    | '/businesses/$businessslug/employees/'
    | '/businesses/$businessslug/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BusinessesBusinessslugRoute: typeof BusinessesBusinessslugRouteWithChildren
  BusinessesRegisterRoute: typeof BusinessesRegisterRoute
  BusinessesSelectBusinessRoute: typeof BusinessesSelectBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/select-business': {
      id: '/businesses/select-business'
      path: '/businesses/select-business'
      fullPath: '/businesses/select-business'
      preLoaderRoute: typeof BusinessesSelectBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/register': {
      id: '/businesses/register'
      path: '/businesses/register'
      fullPath: '/businesses/register'
      preLoaderRoute: typeof BusinessesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessslug': {
      id: '/businesses/$businessslug'
      path: '/businesses/$businessslug'
      fullPath: '/businesses/$businessslug'
      preLoaderRoute: typeof BusinessesBusinessslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessslug/': {
      id: '/businesses/$businessslug/'
      path: '/'
      fullPath: '/businesses/$businessslug/'
      preLoaderRoute: typeof BusinessesBusinessslugIndexRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/groups/': {
      id: '/businesses/$businessslug/groups/'
      path: '/groups'
      fullPath: '/businesses/$businessslug/groups'
      preLoaderRoute: typeof BusinessesBusinessslugGroupsIndexRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/employees/': {
      id: '/businesses/$businessslug/employees/'
      path: '/employees'
      fullPath: '/businesses/$businessslug/employees'
      preLoaderRoute: typeof BusinessesBusinessslugEmployeesIndexRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/groups/create': {
      id: '/businesses/$businessslug/groups/create'
      path: '/groups/create'
      fullPath: '/businesses/$businessslug/groups/create'
      preLoaderRoute: typeof BusinessesBusinessslugGroupsCreateRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/groups/$groupslug': {
      id: '/businesses/$businessslug/groups/$groupslug'
      path: '/groups/$groupslug'
      fullPath: '/businesses/$businessslug/groups/$groupslug'
      preLoaderRoute: typeof BusinessesBusinessslugGroupsGroupslugRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/employees/create': {
      id: '/businesses/$businessslug/employees/create'
      path: '/employees/create'
      fullPath: '/businesses/$businessslug/employees/create'
      preLoaderRoute: typeof BusinessesBusinessslugEmployeesCreateRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
    '/businesses/$businessslug/employees/$employeeid': {
      id: '/businesses/$businessslug/employees/$employeeid'
      path: '/employees/$employeeid'
      fullPath: '/businesses/$businessslug/employees/$employeeid'
      preLoaderRoute: typeof BusinessesBusinessslugEmployeesEmployeeidRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
  }
}

interface BusinessesBusinessslugRouteChildren {
  BusinessesBusinessslugIndexRoute: typeof BusinessesBusinessslugIndexRoute
  BusinessesBusinessslugEmployeesEmployeeidRoute: typeof BusinessesBusinessslugEmployeesEmployeeidRoute
  BusinessesBusinessslugEmployeesCreateRoute: typeof BusinessesBusinessslugEmployeesCreateRoute
  BusinessesBusinessslugGroupsGroupslugRoute: typeof BusinessesBusinessslugGroupsGroupslugRoute
  BusinessesBusinessslugGroupsCreateRoute: typeof BusinessesBusinessslugGroupsCreateRoute
  BusinessesBusinessslugEmployeesIndexRoute: typeof BusinessesBusinessslugEmployeesIndexRoute
  BusinessesBusinessslugGroupsIndexRoute: typeof BusinessesBusinessslugGroupsIndexRoute
}

const BusinessesBusinessslugRouteChildren: BusinessesBusinessslugRouteChildren =
  {
    BusinessesBusinessslugIndexRoute: BusinessesBusinessslugIndexRoute,
    BusinessesBusinessslugEmployeesEmployeeidRoute:
      BusinessesBusinessslugEmployeesEmployeeidRoute,
    BusinessesBusinessslugEmployeesCreateRoute:
      BusinessesBusinessslugEmployeesCreateRoute,
    BusinessesBusinessslugGroupsGroupslugRoute:
      BusinessesBusinessslugGroupsGroupslugRoute,
    BusinessesBusinessslugGroupsCreateRoute:
      BusinessesBusinessslugGroupsCreateRoute,
    BusinessesBusinessslugEmployeesIndexRoute:
      BusinessesBusinessslugEmployeesIndexRoute,
    BusinessesBusinessslugGroupsIndexRoute:
      BusinessesBusinessslugGroupsIndexRoute,
  }

const BusinessesBusinessslugRouteWithChildren =
  BusinessesBusinessslugRoute._addFileChildren(
    BusinessesBusinessslugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BusinessesBusinessslugRoute: BusinessesBusinessslugRouteWithChildren,
  BusinessesRegisterRoute: BusinessesRegisterRoute,
  BusinessesSelectBusinessRoute: BusinessesSelectBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
