/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesSelectBusinessRouteImport } from './routes/businesses/select-business'
import { Route as BusinessesRegisterRouteImport } from './routes/businesses/register'
import { Route as BusinessesBusinessslugRouteImport } from './routes/businesses/$businessslug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as BusinessesBusinessslugIndexRouteImport } from './routes/businesses/$businessslug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSelectBusinessRoute =
  BusinessesSelectBusinessRouteImport.update({
    id: '/businesses/select-business',
    path: '/businesses/select-business',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessesRegisterRoute = BusinessesRegisterRouteImport.update({
  id: '/businesses/register',
  path: '/businesses/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessslugRoute = BusinessesBusinessslugRouteImport.update({
  id: '/businesses/$businessslug',
  path: '/businesses/$businessslug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessslugIndexRoute =
  BusinessesBusinessslugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessesBusinessslugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugRouteWithChildren
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug/': typeof BusinessesBusinessslugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/businesses/$businessslug': typeof BusinessesBusinessslugRouteWithChildren
  '/businesses/register': typeof BusinessesRegisterRoute
  '/businesses/select-business': typeof BusinessesSelectBusinessRoute
  '/businesses/$businessslug/': typeof BusinessesBusinessslugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/$businessslug'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/businesses/$businessslug'
    | '/businesses/register'
    | '/businesses/select-business'
    | '/businesses/$businessslug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  BusinessesBusinessslugRoute: typeof BusinessesBusinessslugRouteWithChildren
  BusinessesRegisterRoute: typeof BusinessesRegisterRoute
  BusinessesSelectBusinessRoute: typeof BusinessesSelectBusinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/select-business': {
      id: '/businesses/select-business'
      path: '/businesses/select-business'
      fullPath: '/businesses/select-business'
      preLoaderRoute: typeof BusinessesSelectBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/register': {
      id: '/businesses/register'
      path: '/businesses/register'
      fullPath: '/businesses/register'
      preLoaderRoute: typeof BusinessesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessslug': {
      id: '/businesses/$businessslug'
      path: '/businesses/$businessslug'
      fullPath: '/businesses/$businessslug'
      preLoaderRoute: typeof BusinessesBusinessslugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessslug/': {
      id: '/businesses/$businessslug/'
      path: '/'
      fullPath: '/businesses/$businessslug/'
      preLoaderRoute: typeof BusinessesBusinessslugIndexRouteImport
      parentRoute: typeof BusinessesBusinessslugRoute
    }
  }
}

interface BusinessesBusinessslugRouteChildren {
  BusinessesBusinessslugIndexRoute: typeof BusinessesBusinessslugIndexRoute
}

const BusinessesBusinessslugRouteChildren: BusinessesBusinessslugRouteChildren =
  {
    BusinessesBusinessslugIndexRoute: BusinessesBusinessslugIndexRoute,
  }

const BusinessesBusinessslugRouteWithChildren =
  BusinessesBusinessslugRoute._addFileChildren(
    BusinessesBusinessslugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  BusinessesBusinessslugRoute: BusinessesBusinessslugRouteWithChildren,
  BusinessesRegisterRoute: BusinessesRegisterRoute,
  BusinessesSelectBusinessRoute: BusinessesSelectBusinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
